### ISSUE TITLE
Failure in building:ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by greenhandzdl** [iains/gcc-darwin-arm64#141]
System Information:
```
~ 
❯ neofetch
                    'c.          greenhandzdl@greenhandzdls-Laptop.local 
                 ,xNMM.          --------------------------------------- 
               .OMMMMo           OS: macOS 15.3 24D60 arm64 
               OMMM0,            Host: Mac15,12 
     .;loddo:' loolloddol;.      Kernel: 24.3.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 5 days, 8 hours, 49 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 209 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1710x1112 @ 60Hz 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: Apple_Terminal 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Menlo-Regular 
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M3 
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M3 
       .cooc,.    .,coo:.        Memory: 2.90GiB / 16.00GiB (18%) 
```
Err Information:
``` 
rm libgcc_s.1.1.dylib_T*
MLIBS=`/opt/gcc/gcc-master-wip-apple-si/temp-gcc/gcc/build/./gcc/xgcc -B/opt/gcc/gcc-master-wip-apple-si/temp-gcc/gcc/build/./gcc/ -B/opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/bin/ -B/opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/lib/ -isystem /opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/include -isystem /opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/sys-include   -fno-checking --print-multi-lib | sed -e 's/;.*$//'` ; \
        for mlib in $MLIBS ; do \
          cp ../${mlib}/libgcc/${mlib}/libgcc_s.dylib  \
            ./libgcc_s.1.1.dylib_T_${mlib} || exit 1 ; \
          arch=`lipo -info libgcc_s.1.1.dylib_T_${mlib} | sed -e 's/.*:\ //'` ; \
          /opt/gcc/gcc-master-wip-apple-si/temp-gcc/gcc/build/./gcc/xgcc -B/opt/gcc/gcc-master-wip-apple-si/temp-gcc/gcc/build/./gcc/ -B/opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/bin/ -B/opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/lib/ -isystem /opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/include -isystem /opt/gcc/gcc-master-wip-apple-si/aarch64-apple-darwin/sys-include   -fno-checking -arch ${arch} -nodefaultlibs -dynamiclib -nodefaultrpaths \
            -o libgcc_s.1.dylib_T_${mlib} \
            -Wl,-reexport_library,libgcc_s.1.1.dylib_T_${mlib} \
            -lSystem \
            -Wl,-reexported_symbols_list,../../../libgcc/config/darwin-unwind.ver \
            -install_name @rpath/libgcc_s.1.dylib \
            -compatibility_version 1 -current_version 1.1 ; \
        done
Undefined symbols for architecture arm64:
  "___deregister_frame_info", referenced from:
      <initial-undefines>
  "___deregister_frame_info_bases", referenced from:
      <initial-undefines>
  "___register_frame_info", referenced from:
      <initial-undefines>
  "___register_frame_info_bases", referenced from:
      <initial-undefines>
  "___register_frame_info_table", referenced from:
      <initial-undefines>
  "___register_frame_info_table_bases", referenced from:
      <initial-undefines>
  "___register_frame_table", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[3]: *** [libgcc_s.1.dylib] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/folders/k6/flv56t9d19g6bxpvl7nhklq40000gn/T//ccUZ5vCK.s:120:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/k6/flv56t9d19g6bxpvl7nhklq40000gn/T//ccUZ5vCK.s:120:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
make[2]: *** [all-stage1-target-libgcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```
Build Script:
```
#!/bin/bash

# 设置 GCC 版本、安装前缀、要编译的语言。
VERSION="master-wip-apple-si"  # 这个版本号可能需要定期更新，以获取最新的 GCC 开发分支
PREFIX="/opt/gcc/gcc-${VERSION}"
LANGUAGES="c,c++,fortran"
# 使用 getconf 获取 CPU 核心数, macOS 上使用 sysctl。  使用 $() 包裹命令可移植性更强。
MAKE="make -j$(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpu)"
sysroot=$(xcrun --show-sdk-path)

# 临时目录，用于下载和构建 GCC
temp_gcc="${PREFIX}/temp-gcc"

# 函数：通过 brew 获取软件包的安装路径 (更具可读性的写法)
brew_path() {
  brew --prefix "$1"
}

# 获取当前机器架构
MACHINE_ARCH=$(uname -m)
echo "Detected architecture: ${MACHINE_ARCH}"

# 根据架构设置默认配置选项
CONFIGURE_OPTIONS=(
  --prefix="${PREFIX}"
  --enable-languages="${LANGUAGES}"
  --with-sysroot="$sysroot"
  --with-gmp="$(brew_path gmp)"
  --with-mpfr="$(brew_path mpfr)"
  --with-mpc="$(brew_path libmpc)"
  --enable-multilingual
  --enable-nls
  --enable-shared
  # --disable-bootstrap  #  如果构建速度过慢，可以取消注释此行以禁用自举编译（但可能会降低优化级别）
)

# 针对 aarch64 (Apple Silicon) 的特殊配置
if [[ "${MACHINE_ARCH}" == "aarch64" ]] || [[ "${MACHINE_ARCH}" == "arm64" ]]; then
  CONFIGURE_OPTIONS+=(--host=aarch64-apple-darwin)
  CONFIGURE_OPTIONS+=(--target=aarch64-apple-darwin)
  CONFIGURE_OPTIONS+=(--build=aarch64-apple-darwin)
fi

# 检查并安装依赖 (使用 brew), 明确检查 gettext
for pkg in gmp mpfr libmpc gettext; do
  if ! brew list "${pkg}" &> /dev/null; then
    echo "正在安装 ${pkg}..."
    brew install "${pkg}"
  fi
done
# 确保 gettext 的 include 目录被添加到 CPATH 中 (有时需要)
# 使用 := 确保只在 CPATH 未定义时设置，避免重复添加。
: "${CPATH:=$(brew --prefix gettext)/include}"
export CPATH

# 检查 make 命令是否存在
if ! command -v make &> /dev/null; then
  echo "错误：未找到 make 命令。请先安装 make。"
  exit 1
fi

# 目录检查和创建, 简化逻辑
if [ ! -d /opt/gcc ]; then
    echo "需要 sudo 权限创建 /opt/gcc"
    sudo mkdir -p /opt/gcc
    sudo chown "$(whoami)":admin /opt/gcc
fi

mkdir -p "${PREFIX}"  # 总是创建 PREFIX 目录
if [[ ! -w "${PREFIX}" ]]; then
    echo "需要 sudo 权限修改 ${PREFIX}"
    sudo chown "$(whoami)":admin "${PREFIX}"
fi

mkdir -p "${temp_gcc}" # 总是创建临时目录

cd "${temp_gcc}" || exit 1

# 询问用户选择下载方式 (只有在 temp_gcc/gcc 不存在时才询问)
if [[ ! -d "gcc" ]]; then  # 只检查 gcc 目录
  while true; do
    read -rp "选择下载方式 (1: git, 2: wget): " choice
    case "${choice}" in
      1)
        DOWNLOAD_METHOD="git"
        GCC_REPO="https://github.com/iains/gcc-darwin-arm64"
        break
        ;;
      2)
        DOWNLOAD_METHOD="wget"
        # 对于 wget 方式，由于我们使用的是 master-wip-apple-si 分支，
        #  GNU FTP 上没有对应的 tar.gz 文件。所以这里需要特别处理。
        #  要么提供一个可用的 tar.gz 下载链接（如果有的话），
        #  要么回退到 git 方式。这里改为提示用户并回退到 git。
        echo "wget 方式不支持 master-wip-apple-si 分支。请选择 git 方式。"
        DOWNLOAD_METHOD="git"
        GCC_REPO="https://github.com/iains/gcc-darwin-arm64"
        break
        ;;
      *)
        echo "无效选择。请输入 1 或 2。"
        ;;
    esac
  done
fi

# 下载 GCC 源码
if [[ "${DOWNLOAD_METHOD}" == "git" ]]; then
  # 直接克隆 master-wip-apple-si 分支
  if [[ ! -d "gcc" ]]; then
    git clone --depth 1 --branch "master-wip-apple-si" "${GCC_REPO}" "gcc"
  fi
elif [[ "${DOWNLOAD_METHOD}" == "wget" ]]; then
  #  因为上面已经处理了 wget 不可用的情况，这里可以省略。但为了完整性，保留一个错误提示。
  echo "错误：wget 方式不支持当前分支。请使用 git 方式。"
  exit 1
fi

cd "gcc" || exit 1
BUILD_DIR="./build"  # 使用相对路径, 因为我们总是克隆到 gcc 目录

mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}" || exit 1

# 配置 GCC
if [[ -f Makefile ]]; then
  make clean
fi

# 使用 ../configure，因为我们在 build 目录中
../configure "${CONFIGURE_OPTIONS[@]}" 2>&1 | tee configure.log

if [[ $? -ne 0 ]]; then
  echo "错误：configure 失败。请查看 configure.log 文件获取详细信息。"
  exit 1
fi

# 构建 GCC
${MAKE} 2>&1 | tee make.log

if [[ $? -ne 0 ]]; then
  echo "错误：make 失败。请查看 make.log 文件获取详细信息。"
  exit 1
fi

# 安装 GCC
sudo ${MAKE} install 2>&1 | tee make_install.log

if [[ $? -ne 0 ]]; then
  echo "错误：make install 失败。请查看 make_install.log 文件获取详细信息。"
  exit 1
fi

echo "GCC 安装完成。请将以下内容添加到您的 shell 配置文件 (例如 ~/.bashrc 或 ~/.zshrc):"
echo "export PATH=\"${PREFIX}/bin:${PATH}\""
echo "export LD_LIBRARY_PATH=\"${PREFIX}/lib:${LD_LIBRARY_PATH}\"" #  更常用的写法
echo 'export LANG="zh_CN.UTF-8"'        # 这些通常不需要设置，除非有特殊需求。
echo 'export LANGUAGE="zh_CN.UTF-8"'     #  本地化通常由系统设置控制。
echo "export LC_MESSAGES=\"${PREFIX}/share/locale\""
```

I want to modify the local language file of gcc. Since the gcc@14 provided by homebrew does not have the flag to enable NLS, I choose to recompile. I am sorry that I cannot provide more information due to my limited level.

**Comment by iains** [comment]
> ```

> Undefined symbols for architecture arm64:
>   "___deregister_frame_info", referenced from:
>       <initial-undefines>
> ```

^^^ this is fixed (see below)

> ```
> # 根据架构设置默认配置选项
> CONFIGURE_OPTIONS=(
>   --prefix="${PREFIX}"
>   --enable-languages="${LANGUAGES}"
>   --with-sysroot="$sysroot"
>   --with-gmp="$(brew_path gmp)"
>   --with-mpfr="$(brew_path mpfr)"
>   --with-mpc="$(brew_path libmpc)"
>   --enable-multilingual
>   --enable-nls
>   --enable-shared
>   # --disable-bootstrap  #  如果构建速度过慢，可以取消注释此行以禁用自举编译（但可能会降低优化级别）
> )
> ```

You might need an option to get `libintl` 

> # 针对 aarch64 (Apple Silicon) 的特殊配置
> if [[ "${MACHINE_ARCH}" == "aarch64" ]] || [[ "${MACHINE_ARCH}" == "arm64" ]]; then
>   CONFIGURE_OPTIONS+=(--host=aarch64-apple-darwin)
>   CONFIGURE_OPTIONS+=(--target=aarch64-apple-darwin)
>   CONFIGURE_OPTIONS+=(--build=aarch64-apple-darwin)
> fi

^^^ this is confusing the configure because you did not say which version of macOS/Darwin you wanted to support - assuming you only want to run on macOS15 ... then:

`--build=aarch64-apple-darwin24` is all you need to add to the configure options (you do not need to add` --host=` and `--target= ` but, if you do, then these should also specify the version - they should all be the same).

> I want to modify the local language file of gcc. Since the gcc@14 provided by homebrew does not have the flag to enable NLS, I choose to recompile.

that should be fine.

As I noted above you might need to provide a path for `libintl` - although it is also possible to build this along with the compiler.  First get the build working :)

**Comment by greenhandzdl** [comment]
For above issues,I make such modifications.
```
CONFIGURE_OPTIONS=(
  --prefix="${PREFIX}"
  --enable-languages="${LANGUAGES}"
  --with-sysroot="$sysroot"
  --with-gmp="$(brew_path gmp)"
  --with-mpfr="$(brew_path mpfr)"
  --with-mpc="$(brew_path libmpc)"
  --with-libintl-prefix="$(brew --prefix gettext)"
  --enable-multilingual
  --enable-nls
  --enable-shared
  # --disable-bootstrap  #  如果构建速度过慢，可以取消注释此行以禁用自举编译（但可能会降低优化级别）
)
```
```
if [[ "${MACHINE_ARCH}" == "aarch64" ]] || [[ "${MACHINE_ARCH}" == "arm64" ]]; then
  CONFIGURE_OPTIONS+=(--host=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'))
fi
```
But some error still occors.
```
config.status: executing default commands
make: *** [all] Error 2
Password:
/bin/sh ../mkinstalldirs /opt/gcc/gcc-master-wip-apple-si /opt/gcc/gcc-master-wip-apple-si
gcc -c -g -O2      -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wno-overlength-strings -pedantic -Wno-long-long   -DHAVE_CONFIG_H -I. -I../../fixincludes -I../include -I../../fixincludes/../include ../../fixincludes/fixincl.c
gcc -c -g -O2      -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wno-overlength-strings -pedantic -Wno-long-long   -DHAVE_CONFIG_H -I. -I../../fixincludes -I../include -I../../fixincludes/../include ../../fixincludes/fixtests.c
gcc -c -g -O2      -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wno-overlength-strings -pedantic -Wno-long-long   -DHAVE_CONFIG_H -I. -I../../fixincludes -I../include -I../../fixincludes/../include ../../fixincludes/fixfixes.c
make[2]: *** No rule to make target `install'.  Stop.
make[1]: *** [install-libbacktrace] Error 2
make[1]: *** Waiting for unfinished jobs....
gcc -c -g -O2      -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wno-overlength-strings -pedantic -Wno-long-long   -DHAVE_CONFIG_H -I. -I../../fixincludes -I../include -I../../fixincludes/../include ../../fixincludes/server.c
make[2]: *** No rule to make target `install'.  Stop.
make[1]: *** [install-libcpp] Error 2
gcc -c -g -O2      -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wno-overlength-strings -pedantic -Wno-long-long   -DHAVE_CONFIG_H -I. -I../../fixincludes -I../include -I../../fixincludes/../include ../../fixincludes/procopen.c
/bin/sh: line 0: cd: ./c++tools: No such file or directory
make[1]: *** [install-c++tools] Error 1
gcc -c -g -O2      -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wno-overlength-strings -pedantic -Wno-long-long   -DHAVE_CONFIG_H -I. -I../../fixincludes -I../include -I../../fixincludes/../include ../../fixincludes/fixlib.c
make[2]: *** No rule to make target `install'.  Stop.
make[1]: *** [install-libdecnumber] Error 2
gcc -c -g -O2      -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wno-overlength-strings -pedantic -Wno-long-long   -DHAVE_CONFIG_H -I. -I../../fixincludes -I../include -I../../fixincludes/../include ../../fixincludes/fixopts.c
make[2]: *** No rule to make target `install'.  Stop.
make[1]: *** [install-libiberty] Error 2
srcdir="../../fixincludes" /bin/sh ../../fixincludes/mkfixinc.sh aarch64-apple-darwin24
sed -e 's/@gcc_version@/15.0.1/' < mkheaders.almost > mkheadersT
mv -f mkheadersT mkheaders
gcc -g -O2        -o fixincl fixincl.o fixtests.o fixfixes.o server.o procopen.o fixlib.o fixopts.o ../libiberty/libiberty.a
clang: error: no such file or directory: '../libiberty/libiberty.a'
make[2]: *** [full-stamp] Error 1
make[1]: *** [install-fixincludes] Error 2
make: *** [install] Error 2
```

**Comment by iains** [comment]
For above issues,I make such modifications.
```
CONFIGURE_OPTIONS=(
  --prefix="${PREFIX}"
  --enable-languages="${LANGUAGES}"
  --with-sysroot="$sysroot"
  --with-gmp="$(brew_path gmp)"
  --with-mpfr="$(brew_path mpfr)"
  --with-mpc="$(brew_path libmpc)"
  --with-libintl-prefix="$(brew --prefix gettext)"
  --enable-multilingual
  --enable-nls
  --enable-shared
  # --disable-bootstrap  #  如果构建速度过慢，可以取消注释此行以禁用自举编译（但可能会降低优化级别）
)
```
```
if [[ "${MACHINE_ARCH}" == "aarch64" ]] || [[ "${MACHINE_ARCH}" == "arm64" ]]; then
  CONFIGURE_OPTIONS+=(--host=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'))
fi
```
^^ this is not what I wrote:

either 

1.  `--build=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'`

or 

2. --build=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'` --host=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'` `--target=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'`

(when you do #1 ... the configure makes the host and target setting to match the build)

**Comment by greenhandzdl** [comment]
Do you mean that I need to remove `--build=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'`?
`--build=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'` is equal to `--build=aarch64-apple-darwin24` in my machine
But in fact,when I run `make distclean` and try to rebuild it,I still meet 2errs.
```
g++ -std=c++14  -I../../libcpp -I. -I../../libcpp/../include -I/opt/homebrew/opt/gettext/include -I../../libcpp/include -I/opt/homebrew/opt/gettext/include -g -W -Wall -Wno-narrowing -Wwrite-strings -Wmissing-format-attribute -pedantic -Wno-long-long  -fno-exceptions -fno-rtti -I../../libcpp -I. -I../../libcpp/../include -I/opt/homebrew/opt/gettext/include -I../../libcpp/include -I/opt/homebrew/opt/gettext/include   -c -o lex.o -MT lex.o -MMD -MP -MF .deps/lex.Tpo ../../libcpp/lex.cc
yes
checking for clock_t... In file included from In file included from ../../libcpp/errors.cc:26../../libcpp/identifiers.cc:
In file included from In file included from ../../libcpp/files.cc../../libcpp/system.h::24In file included from 279:
In file included from ../../libcpp/system.h../../libcpp/charset.cc:21::
:26:
:
In file included from /opt/homebrew/opt/gettext/include/libintl.h../../libcpp/system.h::1089279::
34/opt/homebrew/opt/gettext/include/libintl.hIn file included from :1089:279:
:/opt/homebrew/opt/gettext/include/libintl.h:../../libcpp/system.h1089::279 error: 3434::  error: error: :
expected unqualified-id
/opt/homebrew/opt/gettext/include/libintl.hexpected unqualified-id
expected unqualified-id
 1089 | ch a1089  | 1089c | :1089:r34:  *error: scexpected unqualified-idh
aharetlroc a* ls*es e(tilnotc a_lee t(locale_ (ciant e1089g | ory,t __ciantte g_o_rcya,t ecgoonrsyt,  cchoanrs t*__In file included from lo ../../libcpp/directives.ccc:h22a:
 char *setlocr ale)cIn file included from ../../libcpp/system.h:279c:
o/opt/homebrew/opt/gettext/include/libintl.h:
      |                                  ^*
_nst1089 :34: _error: expected unqualified-id
char *_ _1089l | oc/opt/homebrew/opt/gettext/include/libintl.hh:a1089r: 34*:saetle (ic error: expected ')'
nt __lcoactaelgeo)r
yl,      /opt/homebrew/opt/gettext/include/libintl.ho:c1089ale (int __ acleo:7: | note:                                  ^to match this '(')c
n      | 
                                 ^

ast /opt/homebrew/opt/gettext/include/libintl.h:1089:34: 1089 | ccthar */opt/homebrew/opt/gettext/include/libintl.h error: expected ')'
/opt/homebrew/opt/gettext/include/libintl.h:1089:7: __hleaocalnote: e:)
r      1089 *segtlocal| to match this '('o
                                 ^e
 (riyn,t  : 34/opt/homebrew/opt/gettext/include/libintl.h__cc1089: |  onsattegory, cchar *setlocale (In file included from int __category ,c hcaorn s*t_ _cl../../libcpp/expr.ccocerror: :hale)
      |                                  ^
:o1089:a34r:  *error: __l20expected ')':
In file included from ../../libcpp/system.h:279:
n/opt/homebrew/opt/gettext/include/libintl.h:1089s:t34 :char *expected ')'

/opt/homebrew/opt/gettext/include/libintl.h:1089:7: note: oto match this '('ca/opt/homebrew/opt/gettext/include/libintl.hl:e1089):
7      :|        ^note: 
to match this '('

 1089../../libcpp/system.h | :c error: expected unqualified-id
 1089 | _/opt/homebrew/opt/gettext/include/libintl.hc hh_ar *:s10891089:l34o275c:a38l | chaarr  *setlo: error: expected ')'
e)
/opt/homebrew/opt/gettext/include/libintl.h      :| 1089      ^:
7*:s enote: tto match this '('l
oca../../libcpp/system.hl: 2751089: | c:c38e note: expanded from macro 'setlocale'e (intahar l e*s
__c ategoreytl,o  c275a | l#e  d(ei(fiinn: c onote: nexpanded from macro 'setlocale's
t tc h_a_c  a275t | # dteflioncea lstnree (gionrty ,_ conste t loc_a_ ccategory,l echoanr_*cat(ecateg o*rg_o_eloc asye,t lolclaelr_o)s
      |       ^
y,_ lcoocnale)
e      (scale../../libcpp/system.ht char *__loc:| 275:38      ^:
 tnote:  expanded from macro 'setlocale'c
ha../../libcpp/system.hr: 275*:_38_:l onote: cexpanded from macro 'setlocale'a
le)
      | c      ^ateagle)
      |                                  ^
)
  275 |   #275  | d#e de (locale)
      |                                      ^
/opt/homebrew/opt/gettext/include/libintl.h:1089:34: error: expected ')'
/opt/homebrew/opt/gettext/include/libintl.h:1089:7: ofriyn,e  senote: tto match this '('l
ocalefi../../libcpp/system.hnl(ocaclaet)e g(eo rsye,t llooccaall le1089 | chaor (*csaettelgoocrayl,e  l(incta l_e_)oc:275:38: note: expanded from macro 'setlocale'
  275 | # ca(tleogco define seaale) (lrocya,l ec)o
n      s| tl ec)h
a      r| tl                                     ^o
                                     ^
 *__locale)
      |       ^
../../libcpp/system.h:275:38: note: expanded from macro 'setlocale'
  275 | # define setlocale(category, locale) (locale)
      |                                      ^
e)
      |                                      ^
cale(category, locale) (locale)
      |                                      ^
In file included from ../../libcpp/lex.cc:23:
In file included from ../../libcpp/system.h:279:
/opt/homebrew/opt/gettext/include/libintl.h:1089:34: error: expected unqualified-id
 1089 | char *setlocale (int __category, const char *__locale)
      |                                  ^
/opt/homebrew/opt/gettext/include/libintl.h:1089:34: error: expected ')'
/opt/homebrew/opt/gettext/include/libintl.h:1089:7: note: to match this '('
 1089 | char *setlocale (int __category, const char *__locale)
      |       ^
../../libcpp/system.h:275:38: note: expanded from macro 'setlocale'
  275 | # define setlocale(category, locale) (locale)
      |                                      ^
2 errors generated.
2 errors generated.
In file included from ../../libcpp/directives.cc:25:
../../libcpp/include/mkdeps.h:55:37: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   55 | extern void deps_add_module_target (struct mkdeps *, const char *module,
      |                                     ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
../../libcpp/include/mkdeps.h:60:34: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   60 | extern void deps_add_module_dep (struct mkdeps *, const char *module);
      |                                  ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
../../libcpp/include/mkdeps.h:63:31: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   63 | extern void fdeps_add_target (struIn file included from ../../libcpp/files.cc:27:
../../libcpp/include/mkdeps.h:55:37: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   55 | extern void deps_add_module_target (struct mkdeps *, const char *module,
      |                                     ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
../../libcpp/include/mkdeps.h:60:34: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   60 | extern void deps_add_module_dep (struct mkdeps *, const char *module);
      |                                  ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
../../libcpp/include/mkdeps.h:63:31: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   63 | extern void fdeps_add_target (struct mkdeps *, const char *, bool);
      |                               ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
../../libcpp/include/mkdeps.h:76:39: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   76 | extern void deps_write_p1689r5 (const struct mkdeps *, FILE *);
      |                                       ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
ct mkdeps *, const char *, bool);
      |                               ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
../../libcpp/include/mkdeps.h:76:39: warning: struct 'mkdeps' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   76 | extern void deps_write_p1689r5 (const struct mkdeps *, FILE *);
      |                                       ^
../../libcpp/include/mkdeps.h:31:7: note: previous use is here
   31 | class mkdeps;
      |       ^
make[3]: *** [identifiers.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [errors.o] Error 1
../../libcpp/files.cc:1338:26: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
 1338 |       tok->val.str.len = sprintf ((char *) s, "%d", buffer[i]);
      |                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:274:1: note: 'sprintf' has been explicitly marked deprecated here
  274 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:218:48: note: expanded from macro '__deprecated_msg'
  218 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |                                                       ^
2 errors generated.
make[3]: *** [expr.o] Error 1
54 warnings and 2 errors generated.
 warnings and 2 errors generated.
make[3]: *** [directives.o] Error 1
make[3]: *** [files.o] Error 1
../../libcpp/lex.cc:1308:7: warning: use of the 'likely' attribute is a C++20 extension [-Wc++20-attribute-extensions]
 1308 |       ATTR_LIKELY case kind::NONE:
      |       ^~~~~~~~~~~
../../libcpp/system.h:427:25: note: expanded from macro 'ATTR_LIKELY'
  427 | #  define ATTR_LIKELY [[likely]]
      |                       ~~^~~~~~~~
../../libcpp/lex.cc:4786:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
 4786 |       sprintf ((char *) result, "#%s ", dir_name);
      |       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:274:1: note: 'sprintf' has been explicitly marked deprecated here
  274 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:218:48: note: expanded from macro '__deprecated_msg'
  218 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |                                                       ^
2 warnings and 2 errors generated.

make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```

**Comment by iains** [comment]
> Do you mean that I need to remove `--build=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'`? `--build=aarch64-apple-darwin$(uname -r | awk -F. '{print $1}'` is equal to `--build=aarch64-apple-darwin24` in my machine But in fact,when I run `make distclean` 

I mean that you should specify `--build=aarch64-apple-darwin24` (for macOS15)  either directly or using your awk mechanism.

===

The other errors seem to relate to the gettext package.  I think you need at least `gettext-0.22.5` to be compatible with the C23 changes in trunk GCC.

You can arrange to build this with the compiler by downloading / checking out `gettext-0.22.5` (or newer)and then symlinking it to `gettext` in the top level of the GCC sources.

This is what I do to avoid external dependencies:

e.g in my GCC source directory I have:
`gettext -> ../gcc-prerequisites/gettext-0.22.5`

**Comment by greenhandzdl** [comment]
```
CONFIGURE_OPTIONS=(
  --prefix="${PREFIX}"
  --build="aarch64-apple-darwin$(uname -r | awk -F. '{print $1}')" # Fixed?
  --enable-languages="${LANGUAGES}"
  --with-sysroot="$sysroot"
  --with-gmp="$(brew_path gmp)"
  --with-mpfr="$(brew_path mpfr)"
  --with-mpc="$(brew_path libmpc)"
  --with-libintl-prefix="$(brew --prefix gettext)"
  --enable-multilingual
  --enable-nls
  --enable-shared
  # --disable-bootstrap  #  如果构建速度过慢，可以取消注释此行以禁用自举编译（但可能会降低优化级别）
)
```

```
mkdir sym-exec/.deps
config.status: executing default-1 commands
config.status: executing default commands
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```

**Comment by iains** [comment]
> ```
> CONFIGURE_OPTIONS=(
>   --prefix="${PREFIX}"
>   --build="aarch64-apple-darwin$(uname -r | awk -F. '{print $1}')" # Fixed?
>```

yes, that looks OK to me ..

**Comment by greenhandzdl** [comment]
``` others/SHELL/MAC_BASH on  master [?] took 2m18s 
❯ brew info gettext        
==> gettext: stable 0.23.1 (bottled)
GNU internationalization (i18n) and localization (l10n) library
https://www.gnu.org/software/gettext/
Installed
/opt/homebrew/Cellar/gettext/0.23.1 (2,052 files, 22.2MB) *
  Poured from bottle using the formulae.brew.sh API on 2025-01-13 at 22:01:47
From: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/Formula/g/gettext.rb
License: GPL-3.0-or-later
==> Dependencies
Required: libunistring ✔
==> Analytics
install: 235,924 (30 days), 643,634 (90 days), 2,249,648 (365 days)
install-on-request: 16,834 (30 days), 49,313 (90 days), 131,611 (365 days)
build-error: 111 (30 days)
```
I use gettext 0.23.1,and it still doesn't work.

**Comment by iains** [comment]
OK .. unfortunately, I am tied up this week with WG21 meeting, so it might be a little time before I can investigate more details.  You could try  a build with `gettext-0.25.5` in case there is some new incompatibility.  Otherwise, I will need to look at this next week.

**Comment by iains** [comment]
I did a build on x86_64-apple-darwin24 - with NLS enabled (using `get text-0.22.5` built in-tree).

Probably, I cannot check arm64 until next week ...

```
$ LANG=en_GB /opt/iains/x86_64-apple-darwin24/gcc-15-0-1/bin/gcc
gcc: fatal error: no input files
compilation terminated.

$ LANG=de /opt/iains/x86_64-apple-darwin24/gcc-15-0-1/bin/gcc
gcc: schwerwiegender Fehler: keine Eingabedateien
Kompilierung beendet.

$ LANG=zh_CN /opt/iains/x86_64-apple-darwin24/gcc-15-0-1/bin/gcc
gcc: 致命错误：没有输入文件
编译中断。
```

**Comment by iains** [comment]
I built aarch64-apple-darwin24 using xc16.1 CLT and MacOSX15.sdk (but on macOS14)

```
$ LANG=en_GB /opt/iains/aarch64-apple-darwin24/gcc-15-0-1/bin/g++
g++: fatal error: no input files
compilation terminated.
$ LANG=de /opt/iains/aarch64-apple-darwin24/gcc-15-0-1/bin/g++   
g++: schwerwiegender Fehler: keine Eingabedateien
Kompilierung beendet.
$ LANG=ja_JP /opt/iains/aarch64-apple-darwin24/gcc-15-0-1/bin/g++
g++: 致命的エラー: 入力ファイルがありません
コンパイルを停止しました。
$ LANG=zh_CN /opt/iains/aarch64-apple-darwin24/gcc-15-0-1/bin/g++
g++: 致命错误：没有输入文件
编译中断。
```

**Comment by greenhandzdl** [comment]
I suspect it's my script problem, can I see your compilation instructions?

**Comment by iains** [comment]
> I suspect it's my script problem, can I see your compilation instructions?

extra notes;

* First, you need an installation of the `gettext` tools the `msg*` executables are needed to format and install the translations.
* Second, the i18n only works once the compiler is installed (not in the build directory)
* third, I do not really have anything that special in my configure line (intentionally!):

```
/..../configure --prefix=/...../gcc-15-0-1 --build=x86_64-apple-darwin24 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk   --enable-languages=all CC=... CXX=...
```
Of course, you do not need to have `--enable-languages=all`
(this is obv. on x86_64 Sequoia - but the basic principles should be the same)

You might find this toolset helpful https://github.com/iains/build-scripts (but if you have a homebrew installation, that should work too)

**Comment by greenhandzdl** [comment]
I'll close this issue first, I'll try these scripts, and if they run into problems, I'll report them there.
